/**
 * MobulaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface ErrorResponse {
  error?: string;
}

export const errorResponseSchema: Schema<ErrorResponse> = object({
  error: ['error', optional(string())],
});
